---@type LazySpec
return {
  "nvim-treesitter/nvim-treesitter",
  opts = function(_, opts)
    opts.ensure_installed = require("astrocore").list_insert_unique(opts.ensure_installed, {
      "bash",
      "comment",
      "css",
      "diff",
      "dockerfile",
      "git_config",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "go",
      "html",
      "http",
      "ini",
      "javascript",
      "json",
      "jsonc",
      "lua",
      "make",
      "markdown",
      "passwd",
      "php",
      "phpdoc",
      "python",
      "regex",
      "ruby",
      "rust",
      "sql",
      "svelte",
      "typescript",
      "vim",
      "vue",
      "xml",
      "yaml",
    })
  end,
}
