local operating_system=$(uname -a)
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# zsh completions
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:$FPATH

  autoload -Uz compinit
  compinit
fi

# asdf settings
if [[ $operating_system =~ "Darwin" ]]; then
  . $(brew --prefix asdf)/libexec/asdf.sh
  PATH="$PATH":~/.asdf/installs/rust/stable/bin
else
  . "$HOME/.asdf/asdf.sh"
fi

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# PATH to dotfiles script
PATH=~/.local/bin:$PATH

# lazygit
export XDG_CONFIG_HOME="$HOME/.config"

# Laravel Sail
alias sail='[ -f sail ] && bash sail || bash vendor/bin/sail'

# another configuration for local
if [ -e ~/.zshrc_local ]; then
  source ~/.zshrc_local
fi

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
